import java.util.Vector;
class Main{
public static void main(String args[]){
Vector<String>Groceries=new Vector<>();
Vector<String>fruits=new Vector<>();
fruits.add("mango");
fruits.add("banana");
fruits.add("grapes");
fruits.add("berries");
fruits.add("pineapples");
fruits.add("Coconuts");
Groceries.addAll(fruits);
System.out.println("Vector:"+fruits);
System.out.println("Groceries:"+Groceries);
Vector<String>vegetables=new Vector<>();
vegetables.add("onion");
vegetables.add("tomato");
vegetables.add("chillies");
vegetables.add("ginger");
vegetables.add("garlic");
vegetables.add("peppers");
vegetables.add("broccoil");
vegetables.add("carrots");
vegetables.add("cabbage");
Groceries.addAll(vegetables);
System.out.println("New Vector:\n"+vegetables);
System.out.println("Groceries:"+Groceries);
Vector<String>animalproduce=new Vector<>();
animalproduce.add("chicken");
animalproduce.add("meat");
animalproduce.add("fish");
animalproduce.add("egg");
Groceries.addAll(animalproduce);
System.out.println("New Vector:\n"+animalproduce);
Vector<String>dairyproducts=new Vector<>();
dairyproducts.add("milk");
dairyproducts.add("egg");
dairyproducts.add("cheese");
dairyproducts.add("butter");
Groceries.addAll(dairyproducts);
System.out.println("New Vector:\n"+dairyproducts);
Vector<String>bakeryproducts=new Vector<>();
bakeryproducts.add("whole-wheat-bread");
bakeryproducts.add("kulchas");
bakeryproducts.add("biscuits");
bakeryproducts.add("cakes");
Groceries.addAll(bakeryproducts);
System.out.println("New Vector:\n"+bakeryproducts);
System.out.println("Groceries:"+Groceries);
Vector<String>indianspecies=new Vector<>();
indianspecies.add("cardamom");
indianspecies.add("cinnamon");
indianspecies.add("nutmeg");
indianspecies.add("zeera");
Groceries.addAll(indianspecies);
System.out.println("New Vector:\n"+indianspecies);
System.out.println("Groceries:"+Groceries);
Vector<String>oils=new Vector<>();
oils.add("olive oil");
oils.add("sunflower oil");
oils.add("soy souse");
oils.add("fish souse");
Groceries.addAll(oils);
System.out.println("New Vector:\n"+oils);
System.out.println("Groceries:"+Groceries);
Vector<String>grainslegumes=new Vector<>();
grainslegumes.add("atta");
grainslegumes.add("rice");
grainslegumes.add("pasta");
Groceries.addAll(grainslegumes);
System.out.println("New Vector:\n"+grainslegumes);
System.out.println("Groceries:"+Groceries);
Vector<String>legumes=new Vector<>();
legumes.add("chickpeas");
legumes.add("kidney beans");
legumes.add("lentils");
legumes.add("beans");
Groceries.addAll(legumes);
System.out.println("New Vector:\n"+legumes);
System.out.println("Groceries:"+Groceries);
Vector<String>snacks=new Vector<>();
snacks.add("walnuts");
snacks.add("almonds");
snacks.add("raisins");
snacks.add("honey");
Groceries.addAll(snacks);
System.out.println("New Vector:\n"+snacks);
System.out.println("Groceries:"+Groceries);
Vector<String>cleaningsupplies=new Vector<>();
cleaningsupplies.add("soap");
cleaningsupplies.add("shampoo");
cleaningsupplies.add("tooth paste");
cleaningsupplies.add("tiddue paper");
Groceries.addAll(cleaningsupplies);
System.out.println("New Vector:\n"+cleaningsupplies);
System.out.println("Groceries:"+Groceries);




}
}
